declare module "*.jpg";
declare module "*.png";
declare module "*.pdf";
declare module "*.jpeg";
declare module "*.webp";
declare module "three/examples/jsm/loaders/GLTFLoader";
declare module "*.glb";
declare module "*.gltf";
declare module "three";
